# Generated by Django 5.1.15 on 2026-07-30 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("laptop", "Laptop / Portátil"),
                            ("desktop", "PC de Escritorio"),
                            ("all_in_one", "All-in-One"),
                            ("console", "Consola de Videojuegos"),
                            ("servidor", "Servidor / Workstation"),
                            ("otro", "Otro"),
                        ],
                        default="laptop",
                        max_length=30,
                        verbose_name="Tipo de Equipo",
                    ),
                ),
                ("marca", models.CharField(max_length=80, verbose_name="Marca")),
                (
                    "modelo",
                    models.CharField(max_length=100, verbose_name="Modelo Exacto"),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número de Serie / S/N"
                    ),
                ),
                (
                    "pin_cifrado",
                    models.TextField(
                        blank=True, verbose_name="PIN / Contraseña Cifrada (Fernet)"
                    ),
                ),
                (
                    "procesador",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Procesador"
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Memoria RAM"
                    ),
                ),
                (
                    "almacenamiento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Almacenamiento (SSD/HDD)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipos",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
            },
        ),
    ]
