# Generated by Django 5.1.15 on 2026-07-30 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("core", "0001_initial"),
        ("equipos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistRecepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datos_inspeccion",
                    models.JSONField(
                        default=dict,
                        help_text="Estructura JSON con checklist (pantalla, teclado, bisagras, cargador, encendido, rayones, etc.)",
                        verbose_name="Datos de Inspección Física",
                    ),
                ),
                (
                    "hash_sha256",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        verbose_name="Hash SHA-256 de Inmutabilidad",
                    ),
                ),
                (
                    "timestamp_sellado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Timestamp de Sellado"
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist de Recepción",
                "verbose_name_plural": "Checklists de Recepción",
            },
        ),
        migrations.CreateModel(
            name="Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_orden",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Código de Orden (ORD-AAAA-NNN)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ingresado", "1. Ingresado"),
                            ("en_diagnostico", "2. En diagnóstico"),
                            ("cotizado", "3. Cotizado / Esperando aprobación"),
                            ("aprobado", "4. Aprobado / Repuestos pedidos"),
                            ("en_reparacion", "5. En reparación"),
                            ("en_pruebas", "6. En pruebas (stress test)"),
                            ("listo_entrega", "7. Listo para entrega"),
                            ("entregado_cobrado", "8. Entregado y cobrado"),
                        ],
                        default="ingresado",
                        max_length=30,
                        verbose_name="Estado de la Orden",
                    ),
                ),
                (
                    "motivo_ingreso",
                    models.TextField(
                        verbose_name="Motivo de Ingreso / Fallas Reportadas"
                    ),
                ),
                (
                    "accesorios_incluidos",
                    models.TextField(
                        blank=True,
                        verbose_name="Accesorios Recibidos (Cargador, funda, etc.)",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha y Hora de Ingreso",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes",
                        to="equipos.equipo",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes",
                        to="core.tecnico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Servicio",
                "verbose_name_plural": "Órdenes de Servicio",
                "ordering": ["-fecha_ingreso"],
            },
        ),
        migrations.CreateModel(
            name="FotoEvidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to="evidencias/%Y/%m/",
                        verbose_name="Fotografía de Evidencia",
                    ),
                ),
                (
                    "anotacion",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Anotación / Observación",
                    ),
                ),
                (
                    "hash_sha256",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        verbose_name="Hash SHA-256 de la Imagen",
                    ),
                ),
                (
                    "timestamp_sellado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Timestamp de Carga"
                    ),
                ),
                (
                    "checklist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fotos",
                        to="ordenes.checklistrecepcion",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="ordenes.orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fotografía de Evidencia",
                "verbose_name_plural": "Fotografías de Evidencia",
                "ordering": ["timestamp_sellado"],
            },
        ),
        migrations.AddField(
            model_name="checklistrecepcion",
            name="orden",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist",
                to="ordenes.orden",
            ),
        ),
    ]
