# Generated by Django 5.1.15 on 2026-07-30 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordenes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BitacoraTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "autor_texto",
                    models.CharField(
                        default="Técnico", max_length=100, verbose_name="Registrado por"
                    ),
                ),
                (
                    "contenido",
                    models.TextField(verbose_name="Nota Técnica / Medición / Hallazgo"),
                ),
                (
                    "es_privado",
                    models.BooleanField(
                        default=True, verbose_name="Entrada Privada (Solo Técnico)"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bitacora",
                        to="ordenes.orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitácora Técnica",
                "verbose_name_plural": "Bitácoras Técnicas",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="HistorialEstadoOrden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(max_length=30, verbose_name="Estado Anterior"),
                ),
                (
                    "estado_nuevo",
                    models.CharField(max_length=30, verbose_name="Estado Nuevo"),
                ),
                (
                    "notas_transicion",
                    models.TextField(blank=True, verbose_name="Notas de Transición"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_estados",
                        to="ordenes.orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Estado",
                "verbose_name_plural": "Historial de Estados",
                "ordering": ["timestamp"],
            },
        ),
    ]
