[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Radnar"
bundle = "com.radnar"
version = "0.0.1"

[tool.briefcase.app.radnar]
formal_name = "Radnar App"
description = "Aplicacion Django para radnar"
sources = ["radnar", "config", "apps", "templates", "static", "manage.py"]
license = "MIT"
requires = [
    "django>=5.0,<5.2",
    "djangorestframework>=3.14.0",
    "python-dotenv>=1.0.1",
    "cryptography>=42.0.0",
    "Pillow>=10.2.0",
    "pdf2image>=1.17.0",
    "openpyxl>=3.1.2",
    "reportlab",
    "toga-android~=0.4.4",
]

[tool.briefcase.app.radnar.android]
build_gradle_dependencies = [
    "androidx.appcompat:appcompat:1.6.1",
    "androidx.constraintlayout:constraintlayout:2.1.4",
    "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0",
]
