[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Radnar"
bundle = "com.radnar"
version = "0.0.1"

[tool.briefcase.app.radnar]
formal_name = "Radnar App"
description = "Aplicacion Django para radnar"
sources = ["."]

[tool.briefcase.app.radnar.system.android]
requires = [
    "django>=5.0,<5.2",
    "djangorestframework>=3.14.0",
    "python-dotenv>=1.0.1",
    "cryptography>=42.0.0",
    "Pillow>=10.2.0",
    "pdf2image>=1.17.0",
    "openpyxl>=3.1.2",
    "reportlab",
    "toga-android"
]
