# Generated by Django 5.1.15 on 2026-07-30 15:40

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ordenes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        default="Cotización de Diagnóstico y Reparación",
                        max_length=150,
                        verbose_name="Título de la Cotización",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviada", "Enviada al Cliente"),
                            ("aprobada", "Aprobada por el Cliente"),
                            ("rechazada", "Rechazada por el Cliente"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado de Cotización",
                    ),
                ),
                (
                    "notas_cliente",
                    models.TextField(
                        blank=True, verbose_name="Notas u Observaciones para el Cliente"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotizaciones",
                        to="ordenes.orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LineaCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mano_obra", "Mano de Obra / Servicio Técnico"),
                            ("repuesto", "Repuesto / Componente"),
                            ("equipo_completo", "Equipo Completo / Periférico"),
                        ],
                        default="repuesto",
                        max_length=30,
                        verbose_name="Tipo de Línea",
                    ),
                ),
                (
                    "opcion",
                    models.CharField(
                        choices=[
                            ("opcion_a", "Opción A (Principal / Recomendada)"),
                            ("opcion_b", "Opción B (Alternativa / Económica)"),
                        ],
                        default="opcion_a",
                        max_length=20,
                        verbose_name="Opción de Cotización",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=255,
                        verbose_name="Descripción del Repuesto o Servicio",
                    ),
                ),
                (
                    "costo_proveedor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Costo Proveedor (Privado)",
                    ),
                ),
                (
                    "margen_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("30.00"),
                        max_digits=5,
                        verbose_name="Margen de Ganancia (%)",
                    ),
                ),
                (
                    "precio_cliente",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Precio Unitario Cliente",
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
                (
                    "aprobada_por_cliente",
                    models.BooleanField(
                        default=True, verbose_name="Aprobada en la Cotización"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="cotizaciones.cotizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de Cotización",
                "verbose_name_plural": "Líneas de Cotización",
            },
        ),
        migrations.CreateModel(
            name="EnlaceProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Enlace de Producto"
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(
                        choices=[
                            ("mercadolibre", "MercadoLibre Colombia"),
                            ("amazon", "Amazon"),
                            ("local", "Proveedor Local / Entrada Manual"),
                        ],
                        default="local",
                        max_length=30,
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "titulo_extraido",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Título Extraído del Proveedor",
                    ),
                ),
                (
                    "precio_extraido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Último Precio Extraído",
                    ),
                ),
                (
                    "imagen_url_extraida",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        verbose_name="URL Imagen del Proveedor",
                    ),
                ),
                (
                    "imagen_local",
                    models.ImageField(
                        blank=True,
                        upload_to="proveedores_locales/%Y/%m/",
                        verbose_name="Imagen Local (Proveedor Local)",
                    ),
                ),
                (
                    "ultimo_precio_verificado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Último Precio Verificado",
                    ),
                ),
                (
                    "timestamp_verificacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Timestamp de Verificación"
                    ),
                ),
                (
                    "alerta_cambio_precio",
                    models.BooleanField(
                        default=False, verbose_name="Alerta Visual: Precio Cambió"
                    ),
                ),
                (
                    "linea_cotizacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enlace_proveedor",
                        to="cotizaciones.lineacotizacion",
                    ),
                ),
            ],
        ),
    ]
