import '../models/cliente.dart';
import '../models/equipo.dart';
import '../models/orden.dart';
import '../repositories/cliente_repository.dart';
import '../repositories/equipo_repository.dart';
import '../repositories/orden_repository.dart';

class SeedDataHelper {
  static Future<void> loadSeedData() async {
    final clienteRepo = ClienteRepository();
    final equipoRepo = EquipoRepository();
    final ordenRepo = OrdenRepository();

    // Check if clients already exist to avoid duplicate seed data
    final existingClients = await clienteRepo.getAll();
    if (existingClients.isNotEmpty) {
      return; // Already seeded
    }

    // --- Create Mock Clients ---
    final c1 = Cliente(
      nombreCompleto: 'Carlos Mendoza',
      telefono: '+573001234567',
      email: 'carlos.mendoza@gmail.com',
      direccion: 'Calle 10 # 5-20, Bogotá',
      notas: 'Cliente recurrente. Exigente con los tiempos.',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final c2 = Cliente(
      nombreCompleto: 'María Camila Restrepo',
      telefono: '+573109876543',
      email: 'maria.camila@hotmail.com',
      direccion: 'Avenida 34 # 12A-55, Medellín',
      notas: 'Prefiere ser notificada por WhatsApp.',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final c3 = Cliente(
      nombreCompleto: 'Juan Carlos Pérez',
      telefono: '+573204567890',
      email: 'juan.perez@outlook.com',
      direccion: 'Carrera 7 # 100-24, Cali',
      notas: 'Cliente corporativo (Factura a nombre de empresa).',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final c1Id = await clienteRepo.insert(c1);
    final c2Id = await clienteRepo.insert(c2);
    final c3Id = await clienteRepo.insert(c3);

    // --- Create Mock Devices ---
    final e1 = Equipo.create(
      clienteId: c1Id,
      tipo: 'laptop',
      marca: 'ASUS',
      modelo: 'ROG Strix G15',
      numeroSerie: 'ASUS987654321',
      pinPlano: 'carlos2026',
      procesador: 'AMD Ryzen 7 5800H',
      ram: '16 GB DDR4',
      almacenamiento: '512 GB SSD NVMe',
    );

    final e2 = Equipo.create(
      clienteId: c2Id,
      tipo: 'otro',
      marca: 'Apple',
      modelo: 'iPhone 13 Pro',
      numeroSerie: 'DNPG7765Q0',
      pinPlano: '123456',
      procesador: 'A15 Bionic',
      ram: '6 GB',
      almacenamiento: '128 GB NVMe',
    );

    final e3 = Equipo.create(
      clienteId: c3Id,
      tipo: 'desktop',
      marca: 'Custom Build',
      modelo: 'PC Gamer/Workstation',
      numeroSerie: 'N/A - Armado',
      pinPlano: 'sin_contraseña',
      procesador: 'Intel Core i9-12900K',
      ram: '32 GB DDR5',
      almacenamiento: '2 TB SSD Samsung 980 Pro',
    );

    final e1Id = await equipoRepo.insert(e1);
    final e2Id = await equipoRepo.insert(e2);
    final e3Id = await equipoRepo.insert(e3);

    // --- Create Mock Service Orders ---
    final o1 = Orden(
      codigoOrden: '', // Will be auto-generated by repo
      clienteId: c1Id,
      equipoId: e1Id,
      estado: 'en_diagnostico',
      motivoIngreso: 'El equipo se apaga repentinamente al jugar. Presenta temperaturas superiores a 95°C.',
      accesoriosIncluidos: 'Cargador original Asus de 240W, maletín de transporte.',
      fechaIngreso: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final o2 = Orden(
      codigoOrden: '',
      clienteId: c2Id,
      equipoId: e2Id,
      estado: 'ingresado',
      motivoIngreso: 'Salud de batería al 75%. El puerto de carga a veces no hace contacto.',
      accesoriosIncluidos: 'Cable USB-C a Lightning, estuche protector color rosa.',
      fechaIngreso: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final o3 = Orden(
      codigoOrden: '',
      clienteId: c3Id,
      equipoId: e3Id,
      estado: 'cotizado',
      motivoIngreso: 'Reinstalar Windows 11 Pro, limpieza de componentes, cambio de pasta térmica.',
      accesoriosIncluidos: 'Sólo torre (sin periféricos ni cables).',
      fechaIngreso: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    await ordenRepo.insert(o1);
    await ordenRepo.insert(o2);
    await ordenRepo.insert(o3);
  }
}
