# Generated by Django 5.1.15 on 2026-07-30 15:29

from django.db import migrations, models

import apps.clientes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(max_length=150, verbose_name="Nombre Completo"),
                ),
                (
                    "telefono",
                    models.CharField(
                        help_text="Formato internacional E.164 (ej. +573206672858). Único por cliente.",
                        max_length=20,
                        unique=True,
                        validators=[apps.clientes.models.validate_e164_phone],
                        verbose_name="Teléfono (E.164)",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas Internas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["-created_at"],
            },
        ),
    ]
